---

# groups
# resource_types
# resources
# jobs

resources:
- name: gpupgrade_src
  type: git
  source:
    uri: https://github.com/greenplum-db/gpupgrade.git
    branch: 158153670-spike-ci-gpupgrade
    ignore_paths:
    - README*

- name: gpdb_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: gpaddon_src
  type: git
  source:
    branch: master
    private_key: {{gpaddon-git-key}}
    uri: git@github.com:greenplum-db/gpaddon.git

- name: bin_gpdb_centos7
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: gpdb5-concourse-builds-dev
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos7/bin_gpdb.tar.gz

- name: centos-gpdb-build-7
  type: docker-image
  source:
    repository: pivotaldata/centos7-build
    tag: 'gpdb5-latest'

jobs:
- name: compile_gpdb_centos7
  plan:
  - aggregate:
    - get: gpdb_src
      trigger: true
    - get: gpaddon_src
    - get: centos-gpdb-build-7
  - task: compile_gpdb
    image: centos-gpdb-build-7
    file: gpdb_src/concourse/tasks/compile_gpdb.yml
    params:
      IVYREPO_HOST: {{ivyrepo_host}}
      IVYREPO_REALM: {{ivyrepo_realm}}
      IVYREPO_USER: {{ivyrepo_user}}
      IVYREPO_PASSWD: {{ivyrepo_passwd}}
      CONFIGURE_FLAGS: ""
      TARGET_OS: centos
      TARGET_OS_VERSION: 7
      BLD_TARGETS: "clients loaders"
  - aggregate:
    - put: bin_gpdb_centos7
      params:
        file: gpdb_artifacts/bin_gpdb.tar.gz

- name: unit_test
  plan:
  - get: gpupgrade_src
    trigger: true
  - task: unit_test
    file: gpupgrade_src/concourse/tasks/unit_test.yml

- name: integration_test
  plan:
  - aggregate:
    - get: gpupgrade_src
      trigger: true
    - get: gpdb_src
      passed:
      - compile_gpdb_centos7
    - get: bin_gpdb
      resource: bin_gpdb_centos7
      passed:
      - compile_gpdb_centos7
  - task: integration_test
    file: gpupgrade_src/concourse/tasks/integration_test.yml


