# Copyright (c) 2017-2021 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
    tag: latest
inputs:
  - name: madlib_gpdb5
    path: madlib_source
  - name: gpupgrade_src
  - name: sqldump
  - name: cluster_env_files
run:
  path: gpupgrade_src/ci/scripts/load-dump.sh
