// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub_to_agent.proto

package idl

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpgradePrimariesRequest struct {
	SourceBinDir         string         `protobuf:"bytes,1,opt,name=SourceBinDir,proto3" json:"SourceBinDir,omitempty"`
	TargetBinDir         string         `protobuf:"bytes,2,opt,name=TargetBinDir,proto3" json:"TargetBinDir,omitempty"`
	TargetVersion        string         `protobuf:"bytes,3,opt,name=TargetVersion,proto3" json:"TargetVersion,omitempty"`
	DataDirPairs         []*DataDirPair `protobuf:"bytes,4,rep,name=DataDirPairs,proto3" json:"DataDirPairs,omitempty"`
	CheckOnly            bool           `protobuf:"varint,5,opt,name=CheckOnly,proto3" json:"CheckOnly,omitempty"`
	UseLinkMode          bool           `protobuf:"varint,6,opt,name=UseLinkMode,proto3" json:"UseLinkMode,omitempty"`
	MasterBackupDir      string         `protobuf:"bytes,7,opt,name=MasterBackupDir,proto3" json:"MasterBackupDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpgradePrimariesRequest) Reset()         { *m = UpgradePrimariesRequest{} }
func (m *UpgradePrimariesRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesRequest) ProtoMessage()    {}
func (*UpgradePrimariesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{0}
}

func (m *UpgradePrimariesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesRequest.Unmarshal(m, b)
}
func (m *UpgradePrimariesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesRequest.Marshal(b, m, deterministic)
}
func (m *UpgradePrimariesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesRequest.Merge(m, src)
}
func (m *UpgradePrimariesRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesRequest.Size(m)
}
func (m *UpgradePrimariesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesRequest proto.InternalMessageInfo

func (m *UpgradePrimariesRequest) GetSourceBinDir() string {
	if m != nil {
		return m.SourceBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetTargetBinDir() string {
	if m != nil {
		return m.TargetBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetTargetVersion() string {
	if m != nil {
		return m.TargetVersion
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetDataDirPairs() []*DataDirPair {
	if m != nil {
		return m.DataDirPairs
	}
	return nil
}

func (m *UpgradePrimariesRequest) GetCheckOnly() bool {
	if m != nil {
		return m.CheckOnly
	}
	return false
}

func (m *UpgradePrimariesRequest) GetUseLinkMode() bool {
	if m != nil {
		return m.UseLinkMode
	}
	return false
}

func (m *UpgradePrimariesRequest) GetMasterBackupDir() string {
	if m != nil {
		return m.MasterBackupDir
	}
	return ""
}

type DataDirPair struct {
	SourceDataDir        string   `protobuf:"bytes,1,opt,name=SourceDataDir,proto3" json:"SourceDataDir,omitempty"`
	TargetDataDir        string   `protobuf:"bytes,2,opt,name=TargetDataDir,proto3" json:"TargetDataDir,omitempty"`
	SourcePort           int32    `protobuf:"varint,3,opt,name=SourcePort,proto3" json:"SourcePort,omitempty"`
	TargetPort           int32    `protobuf:"varint,4,opt,name=TargetPort,proto3" json:"TargetPort,omitempty"`
	Content              int32    `protobuf:"varint,5,opt,name=Content,proto3" json:"Content,omitempty"`
	DBID                 int32    `protobuf:"varint,6,opt,name=DBID,proto3" json:"DBID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDirPair) Reset()         { *m = DataDirPair{} }
func (m *DataDirPair) String() string { return proto.CompactTextString(m) }
func (*DataDirPair) ProtoMessage()    {}
func (*DataDirPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{1}
}

func (m *DataDirPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDirPair.Unmarshal(m, b)
}
func (m *DataDirPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDirPair.Marshal(b, m, deterministic)
}
func (m *DataDirPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDirPair.Merge(m, src)
}
func (m *DataDirPair) XXX_Size() int {
	return xxx_messageInfo_DataDirPair.Size(m)
}
func (m *DataDirPair) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDirPair.DiscardUnknown(m)
}

var xxx_messageInfo_DataDirPair proto.InternalMessageInfo

func (m *DataDirPair) GetSourceDataDir() string {
	if m != nil {
		return m.SourceDataDir
	}
	return ""
}

func (m *DataDirPair) GetTargetDataDir() string {
	if m != nil {
		return m.TargetDataDir
	}
	return ""
}

func (m *DataDirPair) GetSourcePort() int32 {
	if m != nil {
		return m.SourcePort
	}
	return 0
}

func (m *DataDirPair) GetTargetPort() int32 {
	if m != nil {
		return m.TargetPort
	}
	return 0
}

func (m *DataDirPair) GetContent() int32 {
	if m != nil {
		return m.Content
	}
	return 0
}

func (m *DataDirPair) GetDBID() int32 {
	if m != nil {
		return m.DBID
	}
	return 0
}

type UpgradePrimariesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradePrimariesReply) Reset()         { *m = UpgradePrimariesReply{} }
func (m *UpgradePrimariesReply) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesReply) ProtoMessage()    {}
func (*UpgradePrimariesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{2}
}

func (m *UpgradePrimariesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesReply.Unmarshal(m, b)
}
func (m *UpgradePrimariesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesReply.Marshal(b, m, deterministic)
}
func (m *UpgradePrimariesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesReply.Merge(m, src)
}
func (m *UpgradePrimariesReply) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesReply.Size(m)
}
func (m *UpgradePrimariesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesReply proto.InternalMessageInfo

type DeleteDirectoriesRequest struct {
	Datadirs             []string `protobuf:"bytes,1,rep,name=datadirs,proto3" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDirectoriesRequest) Reset()         { *m = DeleteDirectoriesRequest{} }
func (m *DeleteDirectoriesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDirectoriesRequest) ProtoMessage()    {}
func (*DeleteDirectoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{3}
}

func (m *DeleteDirectoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDirectoriesRequest.Unmarshal(m, b)
}
func (m *DeleteDirectoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDirectoriesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDirectoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDirectoriesRequest.Merge(m, src)
}
func (m *DeleteDirectoriesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDirectoriesRequest.Size(m)
}
func (m *DeleteDirectoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDirectoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDirectoriesRequest proto.InternalMessageInfo

func (m *DeleteDirectoriesRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

type DeleteDirectoriesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDirectoriesReply) Reset()         { *m = DeleteDirectoriesReply{} }
func (m *DeleteDirectoriesReply) String() string { return proto.CompactTextString(m) }
func (*DeleteDirectoriesReply) ProtoMessage()    {}
func (*DeleteDirectoriesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{4}
}

func (m *DeleteDirectoriesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDirectoriesReply.Unmarshal(m, b)
}
func (m *DeleteDirectoriesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDirectoriesReply.Marshal(b, m, deterministic)
}
func (m *DeleteDirectoriesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDirectoriesReply.Merge(m, src)
}
func (m *DeleteDirectoriesReply) XXX_Size() int {
	return xxx_messageInfo_DeleteDirectoriesReply.Size(m)
}
func (m *DeleteDirectoriesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDirectoriesReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDirectoriesReply proto.InternalMessageInfo

type RenameDirectories struct {
	Source               string   `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	Archive              string   `protobuf:"bytes,2,opt,name=Archive,proto3" json:"Archive,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=Target,proto3" json:"Target,omitempty"`
	ArchiveOnly          bool     `protobuf:"varint,4,opt,name=ArchiveOnly,proto3" json:"ArchiveOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameDirectories) Reset()         { *m = RenameDirectories{} }
func (m *RenameDirectories) String() string { return proto.CompactTextString(m) }
func (*RenameDirectories) ProtoMessage()    {}
func (*RenameDirectories) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{5}
}

func (m *RenameDirectories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameDirectories.Unmarshal(m, b)
}
func (m *RenameDirectories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameDirectories.Marshal(b, m, deterministic)
}
func (m *RenameDirectories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameDirectories.Merge(m, src)
}
func (m *RenameDirectories) XXX_Size() int {
	return xxx_messageInfo_RenameDirectories.Size(m)
}
func (m *RenameDirectories) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameDirectories.DiscardUnknown(m)
}

var xxx_messageInfo_RenameDirectories proto.InternalMessageInfo

func (m *RenameDirectories) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *RenameDirectories) GetArchive() string {
	if m != nil {
		return m.Archive
	}
	return ""
}

func (m *RenameDirectories) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *RenameDirectories) GetArchiveOnly() bool {
	if m != nil {
		return m.ArchiveOnly
	}
	return false
}

type RenameDirectoriesRequest struct {
	Dirs                 []*RenameDirectories `protobuf:"bytes,1,rep,name=Dirs,proto3" json:"Dirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RenameDirectoriesRequest) Reset()         { *m = RenameDirectoriesRequest{} }
func (m *RenameDirectoriesRequest) String() string { return proto.CompactTextString(m) }
func (*RenameDirectoriesRequest) ProtoMessage()    {}
func (*RenameDirectoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{6}
}

func (m *RenameDirectoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameDirectoriesRequest.Unmarshal(m, b)
}
func (m *RenameDirectoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameDirectoriesRequest.Marshal(b, m, deterministic)
}
func (m *RenameDirectoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameDirectoriesRequest.Merge(m, src)
}
func (m *RenameDirectoriesRequest) XXX_Size() int {
	return xxx_messageInfo_RenameDirectoriesRequest.Size(m)
}
func (m *RenameDirectoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameDirectoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenameDirectoriesRequest proto.InternalMessageInfo

func (m *RenameDirectoriesRequest) GetDirs() []*RenameDirectories {
	if m != nil {
		return m.Dirs
	}
	return nil
}

type RenameDirectoriesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameDirectoriesReply) Reset()         { *m = RenameDirectoriesReply{} }
func (m *RenameDirectoriesReply) String() string { return proto.CompactTextString(m) }
func (*RenameDirectoriesReply) ProtoMessage()    {}
func (*RenameDirectoriesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{7}
}

func (m *RenameDirectoriesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameDirectoriesReply.Unmarshal(m, b)
}
func (m *RenameDirectoriesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameDirectoriesReply.Marshal(b, m, deterministic)
}
func (m *RenameDirectoriesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameDirectoriesReply.Merge(m, src)
}
func (m *RenameDirectoriesReply) XXX_Size() int {
	return xxx_messageInfo_RenameDirectoriesReply.Size(m)
}
func (m *RenameDirectoriesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameDirectoriesReply.DiscardUnknown(m)
}

var xxx_messageInfo_RenameDirectoriesReply proto.InternalMessageInfo

type StopAgentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentRequest) Reset()         { *m = StopAgentRequest{} }
func (m *StopAgentRequest) String() string { return proto.CompactTextString(m) }
func (*StopAgentRequest) ProtoMessage()    {}
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{8}
}

func (m *StopAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentRequest.Unmarshal(m, b)
}
func (m *StopAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentRequest.Marshal(b, m, deterministic)
}
func (m *StopAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentRequest.Merge(m, src)
}
func (m *StopAgentRequest) XXX_Size() int {
	return xxx_messageInfo_StopAgentRequest.Size(m)
}
func (m *StopAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentRequest proto.InternalMessageInfo

type StopAgentReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentReply) Reset()         { *m = StopAgentReply{} }
func (m *StopAgentReply) String() string { return proto.CompactTextString(m) }
func (*StopAgentReply) ProtoMessage()    {}
func (*StopAgentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{9}
}

func (m *StopAgentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentReply.Unmarshal(m, b)
}
func (m *StopAgentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentReply.Marshal(b, m, deterministic)
}
func (m *StopAgentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentReply.Merge(m, src)
}
func (m *StopAgentReply) XXX_Size() int {
	return xxx_messageInfo_StopAgentReply.Size(m)
}
func (m *StopAgentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentReply proto.InternalMessageInfo

type CheckSegmentDiskSpaceRequest struct {
	Request              *CheckDiskSpaceRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Datadirs             []string               `protobuf:"bytes,2,rep,name=datadirs,proto3" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CheckSegmentDiskSpaceRequest) Reset()         { *m = CheckSegmentDiskSpaceRequest{} }
func (m *CheckSegmentDiskSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*CheckSegmentDiskSpaceRequest) ProtoMessage()    {}
func (*CheckSegmentDiskSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{10}
}

func (m *CheckSegmentDiskSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSegmentDiskSpaceRequest.Unmarshal(m, b)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSegmentDiskSpaceRequest.Marshal(b, m, deterministic)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSegmentDiskSpaceRequest.Merge(m, src)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_CheckSegmentDiskSpaceRequest.Size(m)
}
func (m *CheckSegmentDiskSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSegmentDiskSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSegmentDiskSpaceRequest proto.InternalMessageInfo

func (m *CheckSegmentDiskSpaceRequest) GetRequest() *CheckDiskSpaceRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CheckSegmentDiskSpaceRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

func init() {
	proto.RegisterType((*UpgradePrimariesRequest)(nil), "idl.UpgradePrimariesRequest")
	proto.RegisterType((*DataDirPair)(nil), "idl.DataDirPair")
	proto.RegisterType((*UpgradePrimariesReply)(nil), "idl.UpgradePrimariesReply")
	proto.RegisterType((*DeleteDirectoriesRequest)(nil), "idl.DeleteDirectoriesRequest")
	proto.RegisterType((*DeleteDirectoriesReply)(nil), "idl.DeleteDirectoriesReply")
	proto.RegisterType((*RenameDirectories)(nil), "idl.RenameDirectories")
	proto.RegisterType((*RenameDirectoriesRequest)(nil), "idl.RenameDirectoriesRequest")
	proto.RegisterType((*RenameDirectoriesReply)(nil), "idl.RenameDirectoriesReply")
	proto.RegisterType((*StopAgentRequest)(nil), "idl.StopAgentRequest")
	proto.RegisterType((*StopAgentReply)(nil), "idl.StopAgentReply")
	proto.RegisterType((*CheckSegmentDiskSpaceRequest)(nil), "idl.CheckSegmentDiskSpaceRequest")
}

func init() { proto.RegisterFile("hub_to_agent.proto", fileDescriptor_9e73bb06acc917d8) }

var fileDescriptor_9e73bb06acc917d8 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x6d, 0xbe, 0x9b, 0x49, 0x29, 0x61, 0x51, 0x53, 0xcb, 0x04, 0x14, 0x2c, 0x0e, 0x11, 0x87,
	0x1c, 0x42, 0x85, 0xc4, 0xb1, 0xa9, 0x85, 0x84, 0x44, 0x69, 0x70, 0x28, 0xd7, 0x6a, 0x63, 0x8f,
	0x92, 0x55, 0x1c, 0xdb, 0xac, 0x37, 0x48, 0x3d, 0x71, 0xe6, 0x97, 0xf0, 0x53, 0xf8, 0x5b, 0xd5,
	0x7e, 0x38, 0xb1, 0x93, 0xf8, 0xe6, 0x79, 0xf3, 0x66, 0x3c, 0x6f, 0xde, 0xd8, 0x40, 0x96, 0x9b,
	0xf9, 0x83, 0x88, 0x1f, 0xe8, 0x02, 0x23, 0x31, 0x4a, 0x78, 0x2c, 0x62, 0x52, 0x63, 0x41, 0x68,
	0x77, 0xfd, 0x90, 0xc9, 0xc4, 0x72, 0x33, 0xd7, 0xb0, 0xf3, 0xaf, 0x0a, 0x97, 0xf7, 0xc9, 0x82,
	0xd3, 0x00, 0xa7, 0x9c, 0xad, 0x29, 0x67, 0x98, 0x7a, 0xf8, 0x6b, 0x83, 0xa9, 0x20, 0x0e, 0x9c,
	0xcd, 0xe2, 0x0d, 0xf7, 0x71, 0xc2, 0x22, 0x97, 0x71, 0xab, 0x32, 0xa8, 0x0c, 0xdb, 0x5e, 0x01,
	0x93, 0x9c, 0x1f, 0x94, 0x2f, 0x50, 0x18, 0x4e, 0x55, 0x73, 0xf2, 0x18, 0x79, 0x07, 0xcf, 0x74,
	0xfc, 0x13, 0x79, 0xca, 0xe2, 0xc8, 0xaa, 0x29, 0x52, 0x11, 0x24, 0x57, 0x70, 0xe6, 0x52, 0x41,
	0x5d, 0xc6, 0xa7, 0x94, 0xf1, 0xd4, 0xaa, 0x0f, 0x6a, 0xc3, 0xce, 0xb8, 0x3b, 0x62, 0x41, 0x38,
	0xca, 0x25, 0xbc, 0x02, 0x8b, 0xf4, 0xa1, 0x7d, 0xb3, 0x44, 0x7f, 0x75, 0x17, 0x85, 0x8f, 0x56,
	0x63, 0x50, 0x19, 0x9e, 0x7a, 0x3b, 0x80, 0x0c, 0xa0, 0x73, 0x9f, 0xe2, 0x57, 0x16, 0xad, 0x6e,
	0xe3, 0x00, 0xad, 0xa6, 0xca, 0xe7, 0x21, 0x32, 0x84, 0xe7, 0xb7, 0x34, 0x15, 0xc8, 0x27, 0xd4,
	0x5f, 0x6d, 0x12, 0x29, 0xa1, 0xa5, 0xa6, 0xdb, 0x87, 0x9d, 0xff, 0x15, 0xe8, 0xe4, 0x5e, 0x2d,
	0x55, 0xe9, 0x4d, 0x18, 0xd0, 0xac, 0xa7, 0x08, 0xee, 0xb4, 0x67, 0xac, 0x6a, 0x5e, 0x7b, 0xc6,
	0x7a, 0x03, 0xa0, 0xcb, 0xa6, 0x31, 0x17, 0x6a, 0x3d, 0x0d, 0x2f, 0x87, 0xc8, 0xbc, 0x2e, 0x50,
	0xf9, 0xba, 0xce, 0xef, 0x10, 0x62, 0x41, 0xeb, 0x26, 0x8e, 0x04, 0x46, 0x42, 0xed, 0xa0, 0xe1,
	0x65, 0x21, 0x21, 0x50, 0x77, 0x27, 0x5f, 0x5c, 0x25, 0xbd, 0xe1, 0xa9, 0x67, 0xe7, 0x12, 0x2e,
	0x0e, 0x2d, 0x4f, 0xc2, 0x47, 0xe7, 0x23, 0x58, 0x2e, 0x86, 0x28, 0xd0, 0x65, 0x1c, 0x7d, 0x11,
	0xe7, 0x8f, 0xc1, 0x86, 0xd3, 0x80, 0x0a, 0x1a, 0x48, 0x6b, 0x2a, 0x83, 0xda, 0xb0, 0xed, 0x6d,
	0x63, 0xc7, 0x82, 0xde, 0x91, 0x3a, 0xd9, 0xf1, 0x0f, 0xbc, 0xf0, 0x30, 0xa2, 0xeb, 0x7c, 0x86,
	0xf4, 0xa0, 0xa9, 0xb5, 0x99, 0x95, 0x99, 0x48, 0xaa, 0xb8, 0xe6, 0xfe, 0x92, 0xfd, 0x46, 0xb3,
	0xa5, 0x2c, 0x94, 0x15, 0x5a, 0xad, 0x39, 0x1d, 0x13, 0x49, 0x7f, 0x0d, 0x45, 0xf9, 0x5f, 0xd7,
	0xfe, 0xe6, 0x20, 0xe7, 0x33, 0x58, 0x07, 0x03, 0x64, 0x92, 0xde, 0x43, 0xdd, 0xcd, 0xe4, 0x74,
	0xc6, 0x3d, 0x75, 0x69, 0x87, 0x64, 0xc5, 0x91, 0x12, 0x8f, 0xf4, 0x91, 0x12, 0x09, 0x74, 0x67,
	0x22, 0x4e, 0xae, 0xe5, 0xb7, 0x66, 0x3a, 0x3b, 0x5d, 0x38, 0xcf, 0x61, 0x92, 0x95, 0x40, 0x5f,
	0x9d, 0xe5, 0x0c, 0x17, 0x6b, 0x8c, 0x84, 0xcb, 0xd2, 0xd5, 0x2c, 0xa1, 0x3e, 0x66, 0xb3, 0x5c,
	0x41, 0x8b, 0xeb, 0x47, 0xb5, 0x94, 0xce, 0xd8, 0x56, 0xe3, 0xa8, 0x9a, 0x7d, 0xb2, 0x97, 0x51,
	0x0b, 0xa6, 0x54, 0x8b, 0xa6, 0x8c, 0xff, 0xd6, 0xa0, 0xa1, 0x06, 0x20, 0x77, 0x70, 0x5e, 0xec,
	0x43, 0xde, 0xee, 0x9a, 0x97, 0x0c, 0x64, 0x5b, 0x47, 0xdf, 0x2f, 0xa5, 0x9c, 0x90, 0x6f, 0xd0,
	0xdd, 0x3f, 0x20, 0xd2, 0x57, 0xfc, 0x92, 0x5f, 0x89, 0x6d, 0x97, 0x64, 0x75, 0xbf, 0xef, 0xc7,
	0xae, 0xe4, 0x75, 0x89, 0x1f, 0xa6, 0xe3, 0xab, 0xb2, 0xb4, 0x6e, 0xf9, 0x09, 0xda, 0x5b, 0x07,
	0xc8, 0x85, 0xe2, 0xee, 0xbb, 0x64, 0xbf, 0xdc, 0x87, 0xb7, 0xd3, 0x1c, 0x5c, 0xb3, 0x99, 0xa6,
	0xec, 0xeb, 0x30, 0xd3, 0x94, 0x7c, 0x04, 0x27, 0xf3, 0xa6, 0xfa, 0xd9, 0x7e, 0x78, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x08, 0x7b, 0x02, 0x1c, 0x99, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	CheckDiskSpace(ctx context.Context, in *CheckSegmentDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error)
	UpgradePrimaries(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error)
	RenameDirectories(ctx context.Context, in *RenameDirectoriesRequest, opts ...grpc.CallOption) (*RenameDirectoriesReply, error)
	StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error)
	DeleteDirectories(ctx context.Context, in *DeleteDirectoriesRequest, opts ...grpc.CallOption) (*DeleteDirectoriesReply, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) CheckDiskSpace(ctx context.Context, in *CheckSegmentDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error) {
	out := new(CheckDiskSpaceReply)
	err := c.cc.Invoke(ctx, "/idl.Agent/CheckDiskSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UpgradePrimaries(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error) {
	out := new(UpgradePrimariesReply)
	err := c.cc.Invoke(ctx, "/idl.Agent/UpgradePrimaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RenameDirectories(ctx context.Context, in *RenameDirectoriesRequest, opts ...grpc.CallOption) (*RenameDirectoriesReply, error) {
	out := new(RenameDirectoriesReply)
	err := c.cc.Invoke(ctx, "/idl.Agent/RenameDirectories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error) {
	out := new(StopAgentReply)
	err := c.cc.Invoke(ctx, "/idl.Agent/StopAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteDirectories(ctx context.Context, in *DeleteDirectoriesRequest, opts ...grpc.CallOption) (*DeleteDirectoriesReply, error) {
	out := new(DeleteDirectoriesReply)
	err := c.cc.Invoke(ctx, "/idl.Agent/DeleteDirectories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	CheckDiskSpace(context.Context, *CheckSegmentDiskSpaceRequest) (*CheckDiskSpaceReply, error)
	UpgradePrimaries(context.Context, *UpgradePrimariesRequest) (*UpgradePrimariesReply, error)
	RenameDirectories(context.Context, *RenameDirectoriesRequest) (*RenameDirectoriesReply, error)
	StopAgent(context.Context, *StopAgentRequest) (*StopAgentReply, error)
	DeleteDirectories(context.Context, *DeleteDirectoriesRequest) (*DeleteDirectoriesReply, error)
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) CheckDiskSpace(ctx context.Context, req *CheckSegmentDiskSpaceRequest) (*CheckDiskSpaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDiskSpace not implemented")
}
func (*UnimplementedAgentServer) UpgradePrimaries(ctx context.Context, req *UpgradePrimariesRequest) (*UpgradePrimariesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradePrimaries not implemented")
}
func (*UnimplementedAgentServer) RenameDirectories(ctx context.Context, req *RenameDirectoriesRequest) (*RenameDirectoriesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameDirectories not implemented")
}
func (*UnimplementedAgentServer) StopAgent(ctx context.Context, req *StopAgentRequest) (*StopAgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAgent not implemented")
}
func (*UnimplementedAgentServer) DeleteDirectories(ctx context.Context, req *DeleteDirectoriesRequest) (*DeleteDirectoriesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDirectories not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_CheckDiskSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSegmentDiskSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CheckDiskSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CheckDiskSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CheckDiskSpace(ctx, req.(*CheckSegmentDiskSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UpgradePrimaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradePrimariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UpgradePrimaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/UpgradePrimaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UpgradePrimaries(ctx, req.(*UpgradePrimariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RenameDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameDirectoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RenameDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/RenameDirectories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RenameDirectories(ctx, req.(*RenameDirectoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/StopAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StopAgent(ctx, req.(*StopAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDirectoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/DeleteDirectories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteDirectories(ctx, req.(*DeleteDirectoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDiskSpace",
			Handler:    _Agent_CheckDiskSpace_Handler,
		},
		{
			MethodName: "UpgradePrimaries",
			Handler:    _Agent_UpgradePrimaries_Handler,
		},
		{
			MethodName: "RenameDirectories",
			Handler:    _Agent_RenameDirectories_Handler,
		},
		{
			MethodName: "StopAgent",
			Handler:    _Agent_StopAgent_Handler,
		},
		{
			MethodName: "DeleteDirectories",
			Handler:    _Agent_DeleteDirectories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub_to_agent.proto",
}
