---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.10.3'

inputs:
- name: gpupgrade_src
  path: go/src/github.com/greenplum-db/gpupgrade

# ouputs:
# caches:

run:
  path: go/src/github.com/greenplum-db/gpupgrade/concourse/scripts/unit_test.sh
