name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint specified without patch version
          version: v1.26
